// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACascader: typeof import('ant-design-vue/es')['Cascader']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    APopover: typeof import('ant-design-vue/es')['Popover']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    BodyCell: typeof import('./src/components/draggableTable/bodyCell.vue')['default']
    DraggableTable: typeof import('./src/components/draggableTable/index.vue')['default']
    DurationInput: typeof import('./src/components/durationInput/index.vue')['default']
    EditModalDemo: typeof import('./src/components/loaddingModal/editModalDemo.vue')['default']
    HeaderCell: typeof import('./src/components/draggableTable/headerCell.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InfoTips: typeof import('./src/components/infoTips/index.vue')['default']
    LoaddingModal: typeof import('./src/components/loaddingModal/index.vue')['default']
  }
}

export { }
